/**
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.apache.hadoop.yarn.conf;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.io.Text;

public class YarnConfiguration extends Configuration {

  public static final String RM_PREFIX = "yarn.server.resourcemanager.";
  
  public static final String AM_FAIL_COUNT_STRING = "<FAILCOUNT>";
  
  public static final String ZK_ADDRESS = RM_PREFIX + "zookeeper.address";
  
  public static final String ZK_SESSION_TIMEOUT = RM_PREFIX 
    + "zookeeper.session.timeout";
  
  public static final String SCHEDULER_ADDRESS = RM_PREFIX
      + "scheduler.address";    
  
  public static final String ADMIN_ADDRESS = RM_PREFIX + "admin.address";

  public static final String AM_EXPIRY_INTERVAL = RM_PREFIX
  + "application.expiry.interval";
  
  public static final String AM_MAX_RETRIES = RM_PREFIX 
  + "application.max.retries";
  
  public static final int DEFAULT_ZK_TIMEOUT = 60000;
  
  public static final int DEFAULT_AM_MAX_RETRIES = 3;
  
  public static final long DEFAULT_AM_EXPIRY_INTERVAL = 60000L;
  
  public static final String NM_EXPIRY_INTERVAL = RM_PREFIX 
  + "nodemanager.expiry.interval";
  
  public static final long DEFAULT_NM_EXPIRY_INTERVAL = 600000L;
  
  public static final String DEFAULT_SCHEDULER_BIND_ADDRESS = "0.0.0.0:8030";

  public static final String DEFAULT_ADMIN_BIND_ADDRESS = "0.0.0.0:8141";

  public static final String APPSMANAGER_ADDRESS = RM_PREFIX
      + "appsManager.address";

  public static final String DEFAULT_APPSMANAGER_BIND_ADDRESS =
      "0.0.0.0:8040";

  private static final String YARN_DEFAULT_XML_FILE = "yarn-default.xml";
  private static final String YARN_SITE_XML_FILE = "yarn-site.xml";
  
  public static final String MASTER_KEYS_DIR = "/master_keys_dir";

  public static final String APPLICATION_MANAGER_PRINCIPAL =
      "yarn.jobmanager.user-name";

  public static final String RM_WEBAPP_BIND_ADDRESS = RM_PREFIX
      + "webapp.address";

  public static final String DEFAULT_RM_WEBAPP_BIND_ADDRESS = "0.0.0.0:8088";

  static {
    Configuration.addDefaultResource(YARN_DEFAULT_XML_FILE);
    Configuration.addDefaultResource(YARN_SITE_XML_FILE);
  }

  // The FS delegation tokens' storage on the remote FS. To be written by the
  // job-submitter and to be readable by the job-localizer.
  // TODO: remove
  public static final String FS_TOKENS_FILE_NAME = "fs-token-storage";

  public static final String MASTER_KEY_FILE_NAME =
      "master_key_file";

  // TODO: This should go away once RM and NM share master key directly
  public static final Text RMNMMasterKeyAliasName = new Text("masterKeyAliasName");

  // The token file for the application. Should contain tokens for access to
  // remote file system and may optionally contain application specific tokens.
  // For now, generated by the AppManagers and used by NodeManagers and the
  // Containers.
  public static final String APPLICATION_TOKENS_FILE =
      "appTokens";

  public static final String RM_SERVER_PRINCIPAL_KEY =
      "yarn.resourcemanager.principal";

  public static final String APPLICATION_MASTER_TOKEN_ENV_NAME =
      "AppMasterTokenEnv";

  public static final String APPLICATION_CLIENT_SECRET_ENV_NAME =
      "AppClientTokenEnv";

  public static final String RESOURCE_SCHEDULER = RM_PREFIX + "scheduler";
  
  public static final String RM_STORE = RM_PREFIX + "store";
  
  public YarnConfiguration() {
    super();
  }
  
  public YarnConfiguration(Configuration conf) {
    super(conf);
  }
}
